name: run-tests
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/TurboGears/tempita
          pip install git+https://github.com/TurboGears/tg2@development
          pip install -U --upgrade-strategy=eager --pre -e .[testing]
      - name: Test with unittest
        run: |
          python -m unittest discover -v devtools/tests -f
